def hipphipp() -> None:
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")
    print("Hipp hipp hurra!")

hipphipp()